sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
before_install: gem install bundler
install: bundle
script:
  - bundle exec rspec
deploy:
  provider: rubygems
  api-key: $RUBYGEMS_API_KEY
  on:
    tags: true
    rvm: 2.5.1
